# Imagem base
FROM openjdk:11-jdk-alpine

# Diretório de trabalho
WORKDIR /build

# Copia os arquivos necessários para dentro do container
COPY target/build.jar build.jar

# Porta exposta pelo container
EXPOSE 8080

# Comando de inicialização
CMD ["java", "-jar", "build.jar"]