name: Build Test
on:
  push:
  pull_request:
    types:
      - opened
      - edited

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        name: Checkout
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run test and building
        run: ./gradlew clean compileJava jar
