name: Deploy to ECS

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: us-east-1
  IMAGE_NAME: hackaton-image
  ECS_CLUSTER: hackaton_cluster
  ECS_SERVICE: hackaton-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ env.AWS_REGION }}

      - name: Build and tag Docker image
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Login to AWS ECR
        env:
          AWS_REGION: us-east-1
          ECR_REGISTRY: 178675768868.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: hackaton_repo
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} | aws configure --profile user1 --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }}
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} | aws configure --profile user1 --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Push Docker image to ECR
        id: push-image
        env:
          IMAGE_TAG: ${{ github.sha }}
          LOGIN_SERVER: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push ${{ env.LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Update ECS service
        uses: aws-actions/amazon-ecs-deploy@v2
        with:
          region: ${{ env.AWS_REGION }}
          cluster: ${{ env.ECS_CLUSTER }}
          service: ${{ env.ECS_SERVICE }}
          image: ${{ env.LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}